### PR TITLE
Czech translation for FillUp

### PR DESCRIPTION
**Pull request by svetlemodry**

### CODE REVIEW

**Comment by wdkapps** [comment]
Hello...thanks for your contribution! I will merge it into the repository
soon.

Bill

**Comment by svetlemodry** [comment]
Hey,
any chance to have this PR included then?
Cheers!

**Comment by svetlemodry** [comment]
Hey,
any chance to have this PR included then?
Cheers :D

**Comment by svetlemodry** [comment]
Seems not to be happening, I'll be deleting the forked repo then.

**Pull request closed without merging**
